# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b77aed6da0ab7c3a3cf8babb993b35d989650b01608242010a343dfadc61480877c46bf7383af7bdb655b802a374422abea555c9dc5e129efd21dd5adfa88d60

test:
  secret_key_base: fb101b807585908b86995bdbc200f9f12490aab192967c5f8994039e14d47b20e6deab4caf814f7d4095fb35ba2866201f2d7b9cfb7fa70e386989252dee7fb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
